apiVersion: v1
kind: PersistentVolume
metadata:
  name: guac-config-volume
  namespace: guacamole
  labels:
    type: local
    app: guacamole
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/guacamole
