
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-volume-claim
  namespace: guacamole
  labels:
    app: guacamole
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
